title: Mocking Eye
baseurl: ""
subtitle: "'Tis all in vain?"
author: Michael Katsevman
simple_search: http://google.com/search
description: Description
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /posts/:year/:month/:day/:title
timezone: America/Los_Angeles 
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/page/page:num/"